language: android

android:
  components:
    - build-tools-19.0.0
    - build-tools-19.1.0
    - android-8
    - android-19


script:
# - brew install gradle
# - sudo add-apt-repository ppa:cwchien/gradle
# - sudo apt-get update
# - sudo apt-get install gradle
- gradle wrapper
- echo $ANDROID_HOME
- ls
- sudo bash ./gradlew packageRelease


deploy:
  provider: releases
  file:
    TestFairyApp/build/outputs/apk/TestFairyApp-release-unaligned.apk
before_install:
- openssl aes-256-cbc -K $encrypted_381106421151_key -iv $encrypted_381106421151_iv
  -in testfairy.keystore.enc -out testfairy.keystore -d
