language: android
jdk:
  - oraclejdk7
  - openjdk7
  
android:
  components:
    - build-tools-20.0.0
    - android-19

script: bash gradlew packageRelease --info


deploy:
  provider: releases
  file:
    TestFairyApp/build/outputs/apk/TestFairyApp-release-unaligned.apk
before_install:
- openssl aes-256-cbc -K $encrypted_381106421151_key -iv $encrypted_381106421151_iv
  -in testfairy.keystore.enc -out testfairy.keystore -d