language: android
jdk:
  - openjdk7

android:
  components:
  - build-tools-20.0.0
  - android-19

before_install:
  - openssl aes-256-cbc -K $encrypted_ab387d2e1d9a_key -iv $encrypted_ab387d2e1d9a_iv -in testfairy.keystore.enc -out testfairy.keystore -d

script:
  - bash gradlew assembleRelease --info

deploy:
  provider: releases
  api_key:
    secure: KVoRsyzmMV9p2k0yaZtkdCaP1zB6nB8lOJ03rGGvEX2QoDd3VlzpaQEYtsXz9fKGrGY9kicV6ZO4dGmP4joNukyLMEvuc2++X9K1GL1MhSyKUO1ITeLdU+3LZrBwRSUUMUwkw7sQ7WgcRTkBFeDlyGyLsMVaepPaKMrDIvYMVxs=
  file: TestFairyApp/build/outputs/apk/TestFairyApp-release.apk
  skip_cleanup: true
  on:
    repo: testfairy/testers-app-android
