language: android
jdk:
  - oraclejdk7
  - openjdk7
  
android:
  components:
    - build-tools-20.0.0
    - android-19

script: bash gradlew packageRelease --info


deploy:
  all_branches: true
  provider: releases
  api-key:
    secure: "INsxSD8tXGCPahwC1wETmgVaXXXZgcR6ZWi+TgUB6pCFmtDuIusIJWowbOH4ytRcqtCezmLAjUTdNBverx3+xRGCpHdMbhvaXk1PQYfWnzuLKjSdADPqdIewvpTV2sEXt8dh5+APesgISSG7bJhB83jYFnt07Eux52BwjmCzbD4="
  file:
    TestFairyApp/build/outputs/apk/TestFairyApp-release-unaligned.apk
before_install:
- openssl aes-256-cbc -K $encrypted_381106421151_key -iv $encrypted_381106421151_iv
  -in testfairy.keystore.enc -out testfairy.keystore -d
